[package]
name = "rust-aoc-2024"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "day01"
path = "src/days/d01.rs"

[[bin]]
name = "day02"
path = "src/days/d02.rs"

[[bin]]
name = "day03"
path = "src/days/d03.rs"

[dependencies]
regex = "1.11.1"

